### ISSUE TITLE
Automate software provisioning

### ISSUE THREAD

**Issue by anadahz** [PrivacyLx/privacylx-issue-tracker#15]
This issue is about automate the software provision of all components and services used in the PrivacyLx group. Ideally upon the introduction of a new service or resource deployed a role should be created.
 
We could use Ansible playbooks but let's keep this open in case we have a better plan or another technology that suits us better. 

I have identified the following components/services that require a deployment role strategy:
- [x] Website deployment role (#16)
- [x] Updating servers/services role (#17)
- [x] User management role (#18)
